---
root: true
env:
  browser: false
  es6: true
  node: true
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
extends:
  - plugin:compat/recommended
  - plugin:prettier/recommended
  - prettier
plugins:
  - prettier
